# This file was generated by GoReleaser. DO NOT EDIT.
class Tldr < Formula
  desc "Simplified and community-driven man pages (tldr-pages)."
  homepage "https://github.com/litianqi1996/homebrew-taps"
  version "0.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/litianqi1996/tldr-cli/releases/download/v0.5/tldr_0.5_Darwin_x86_64.tar.gz"
    sha256 "309bc4873e3a2c128205d62f02c5ea7c6ddec03020e9dee57f304b1c4313364c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/litianqi1996/tldr-cli/releases/download/v0.5/tldr_0.5_Linux_x86_64.tar.gz"
      sha256 "3bb5b7642010c4d520bb9d21d2c5ee7b0baeb29d3b8c9465c1de23a85b61499d"
    end
  end

  def install
    bin.install "tldr"
  end

  test do
    system "#{bin}/tldr -version"
  end
end
